services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: assessment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  web:
    build: .
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
