# Generated by Django 5.1.4 on 2026-05-07 19:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('small_business', 'Small Business'), ('startup', 'Startup'), ('corporate', 'Corporate')], db_index=True, max_length=20)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('stock_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
